version: "3"

services:
  php-fpm:
    image: php:7.3-fpm
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
